# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [10]:
print("Version: ",np.__version__)


Version:  1.19.5


In [15]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**3. Create a 1D array of zeros of size 10 of type float32**

In [17]:
d = np.zeros(10, dtype='float32')

**4. Print the memory size of the array below**

In [20]:
Z = np.zeros((32,12))
# Include your solution below
memory = Z.size * Z.itemsize
print("Memory size of array Z in bytes is: ", memory)

Memory size of array Z in bytes is:  3072


**5. Create a 1D array with values ranging from 10 to 58**

In [28]:
np.arange(10,59)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

**6. Reverse the order of the values in the vector (first element becomes last)**

In [46]:
a = np.arange(10)
# Include your solution below
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [56]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**8. Create a 3x3 identity matrix**

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. Find and print the maximum values of each column in the array below** 

In [75]:
Z = np.random.random((10,11))
# Include your solution below

#Will show values in a dataframe for easier viewing and checking
import pandas as pd
pd.DataFrame(Z)

0         1         2         3         4         5         6   \
0  0.447737  0.116763  0.700128  0.865398  0.210769  0.306645  0.752150   
1  0.676177  0.616941  0.909299  0.153384  0.138592  0.670452  0.146752   
2  0.411315  0.485318  0.904902  0.354820  0.422447  0.376920  0.917712   
3  0.336081  0.584089  0.500862  0.837444  0.963381  0.023801  0.488506   
4  0.463811  0.475100  0.646763  0.524077  0.284505  0.777642  0.330141   
5  0.892317  0.961988  0.488988  0.519583  0.143115  0.550947  0.416747   
6  0.124895  0.104307  0.145878  0.320703  0.790923  0.199344  0.495470   
7  0.276537  0.253971  0.420994  0.428324  0.184869  0.952247  0.541780   
8  0.057474  0.315225  0.206293  0.181973  0.243424  0.608259  0.512047   
9  0.482636  0.455557  0.724533  0.724414  0.134771  0.469404  0.010528   

         7         8         9         10  
0  0.110675  0.826520  0.572527  0.081341  
1  0.698106  0.954123  0.243758  0.362036  
2  0.145894  0.113701  0.487799  0.030324  
3  0.593747  0.641981  0.569293  0.888814  
4  0.778743  0.460855  0.580694  0.545583  
5  0.637977  0.468244  0.531170  0.504148  
6  0.668984  0.169627  0.181427  0.492381  
7  0.658735  0.289211  0.167664  0.410637  
8  0.506882  0.846673  0.903404  0.275593  
9  0.745528  0.804365  0.279015  0.371136

In [76]:
#Maximum values in each column shown in an array
print(np.amax(Z,axis=0))

[0.89231748 0.9619878  0.90929913 0.8653979  0.96338063 0.95224683
 0.91771219 0.77874303 0.95412254 0.90340377 0.88881408]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [87]:
a = np.zeros(49).reshape(7,7)
a[0,:]=1
a[:,0]=1
a[-1,:]=1
a[:,-1]=1
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [91]:
Z = np.ones((5,5))
# Include your solution below

np.pad(Z, 2,'constant',constant_values=0)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [97]:
Z = np.random.uniform(0,10,10)
# Include your solution below

np.set_printoptions(suppress=True, precision=0)
print('Z:', Z)

Z: [ 7.  1.  7.  5.  9.  6.  5.  6.  9. 10.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [102]:
a = np.arange(5)
np.tile(a,[5,1])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [107]:
np.set_printoptions(suppress=True, precision=3)
a = np.linspace(0,1,10)
a

array([0.   , 0.111, 0.222, 0.333, 0.444, 0.556, 0.667, 0.778, 0.889,
       1.   ])

**15. Create a random vector of size 10 and sort it**

In [117]:
a = np.random.random(10)
a.sort()
a

array([0.075, 0.097, 0.344, 0.564, 0.602, 0.743, 0.832, 0.871, 0.876,
       0.93 ])

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [128]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(X[0],Y[0],R[0],T[0])

0.06927823269490185 0.9841925021472738 0.9866277691248309 1.500521304740927


**17. Create random vector of size 10 and replace the maximum value by 0**

In [139]:
a = np.random.random(10)
print("Original vector: ",a)
print("Modified vector: ",np.where(a==np.amax(a),0,a))

Original vector:  [0.241 0.468 0.554 0.682 0.855 0.784 0.359 0.645 0.66  0.639]
Modified vector:  [0.241 0.468 0.554 0.682 0.    0.784 0.359 0.645 0.66  0.639]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [140]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
Z

array([0.108, 0.936, 0.549, 0.391, 0.061, 0.796, 0.92 , 0.1  , 0.814,
       0.813])

**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
Z = np.arange(5)[::-1]
# Include your solution below


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    